Import('RTT_ROOT')
Import('rtconfig')
from building import *

src = []
cwd = GetCurrentDir()

# ------------- Sensor device -------------
if GetDepend(['RT_USING_ZSC31014']):
    src += ['sensor_zsc31014.c']
#    src += ['sensor_zsc31014.c', 'zsc31014.c']
    
CPPPATH = [cwd]

group = DefineGroup('Sensors', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
