Import('RTT_ROOT')
Import('rtconfig')
from building import *

src = []
cwd = GetCurrentDir()

# ------------- Sensor device -------------
if GetDepend(['RT_USING_ZSC31014']):
    src += ['sen_zsc31014.c']
    
if GetDepend(['RT_USING_SI114X']):
    src += ['sen_si114x.c', 'libraries/Si114x.c']

CPPPATH = [cwd, cwd + '/libraries']

group = DefineGroup('Sensors', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
