Import('RTT_ROOT')
Import('rtconfig')
from building import *

objs = []
cwd = GetCurrentDir()


# add the general drivers.
src = Split("""
	board.c
    hdl_interrupt.c
    drv_dma.c
""")

#pm driver
if GetDepend(['RT_USING_PM']):
	src +=['emodes.c', 'drv_pm.c']

if GetDepend(['EFM32_USING_LETIMER0_COMPENSATION']):
    src +=['drv_pmtimer.c']
	
#ebi driver
if GetDepend(['RT_USING_EBI']):
    src +=['drv_ebi.c']

#gpio driver
if GetDepend(['RT_USING_PIN']):
    src += ['drv_pin.c']

#i2c bus driver
if GetDepend(['RT_USING_I2C']):
    src += ['drv_iic.c']
	
#spi bus driver
if GetDepend(['RT_USING_SPI']):
	src += ['drv_spi.c']

#wdt driver
if GetDepend(['RT_USING_WDT']):
    src += ['drv_wdt.c']

#letimer driver
if GetDepend(['RT_USING_LETIMER0']):
    src += ['drv_letimer.c']

#timer driver
if (GetDepend(['RT_USING_TIMER0']) or GetDepend(['RT_USING_TIMER1']) or GetDepend(['RT_USING_TIMER2'])):
    src += ['drv_timer.c']

#leuart driver
if (GetDepend(['RT_USING_LEUART0']) or GetDepend(['RT_USING_LEUART1'])):
    src += ['drv_leuart.c']

#usart driver
if (GetDepend(['RT_USING_USART0']) or GetDepend(['RT_USING_USART1']) or GetDepend(['RT_USING_USART2']) or GetDepend(['RT_USING_UART0']) or GetDepend(['RT_USING_UART1'])):
#if (GetDepend(['RT_USING_USART0']) or GetDepend(['RT_USING_USART1']) or GetDepend(['RT_USING_USART2']) or GetDepend(['RT_USING_UART0']) or GetDepend(['RT_USING_UART1']) or GetDepend(['RT_USING_LEUART0']) or GetDepend(['RT_USING_LEUART1'])):
	src += ['drv_serial.c']

#usb device driver
if GetDepend(['RT_USING_USB_DEVICE']):
    src += ['drv_usbd.c','cdc_echo.c','descriptors.c']

#memory lcd device
if GetDepend(['RT_USING_LS027B7DH']):
    src += ['dev_ls027b7dh.c']

#w25qxx device
if GetDepend(['RT_USING_W25QXX']):
    src += ['dev_w25qxx.c']

#BlueMod SR device
if GetDepend(['RT_USING_BLUEMOD_SR']):
    src += ['dev_bluemod_sr.c']

#internal RTC
#if GetDepend(['RT_USING_RTC']):
#    src += ['drv_rtc.c']

#RX8025 device
if GetDepend(['RT_USING_RX8025']):
    src += ['dev_rx8025.c']

#RX8803 device
if GetDepend(['RT_USING_RX8803']):
    src += ['dev_rx8803.c']

#SRAM device
if GetDepend(['RT_USING_EXT_SRAM']):
    src += ['dev_sram.c']

#NAND device
if GetDepend(['RT_USING_EXT_NAND']):
    src += ['dev_nand.c']
    
CPPPATH = [cwd]

objs = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
